### ISSUE TITLE
color scheme detection glitchy

### ISSUE THREAD

**Issue by ShatteredSkies** [luisbocanegra/kde-material-you-colors#118] opened 2022-12-07 17:19 UTC
**Describe the bug**
script gets confused when color scheme is changed while it is still applying themes, instantly switching the theme back.

switching to light color scheme and instantly switching to dark color scheme, script switches color scheme back to light.

**Expected behavior**
script should switch to current color scheme.

**Screenshots**
![screenshot_edit](https://user-images.githubusercontent.com/56289692/206240773-6b5b7dbb-6ad7-4682-8f0f-7fbecc2f39ea.png)

**Comment by luisbocanegra** [comment] 2022-12-07 20:12
Thanks for reporting this, didn't notice because I mainly use dark theme and was switching from config file while testing the light one. Will take a look into it soon.

**Comment by luisbocanegra** [comment] 2022-12-08 10:46
Can you try to reproduce the error again in that branch?

**Comment by luisbocanegra** [comment] 2022-12-08 11:59
Might be related to #92

**Comment by ShatteredSkies** [comment] 2022-12-08 13:10
> Can you try to reproduce the error again in that branch?

just checked, the same problem still exists.

**Comment by luisbocanegra** [comment] 2022-12-08 13:33
> **Describe the bug** script gets confused when color scheme is changed while it is still applying themes, instantly switching the theme back.
> 
> switching to light color scheme and instantly switching to dark color scheme, script switches color scheme back to light.
> 

Hmm, so if you switch light/dark in Koi **after** the script finished switching the selected theme stays right?

**Comment by ShatteredSkies** [comment] 2022-12-08 13:37
> 

that's correct

**Comment by luisbocanegra** [comment] 2022-12-08 13:46
Good, at least it sticks if you don't do it too fast... so don't 👍 . 
Joking, will see if an additional check can be added so it doesn't go crazy.

**Comment by luisbocanegra** [comment] 2022-12-08 14:21
What's your configuration?
If you don't specify for the script (in the config or flags) to use light or dark mode it should follow the plasma theme

**Comment by ShatteredSkies** [comment] 2022-12-08 17:27
> What's your configuration? If you don't specify for the script (in the config or flags) to use light or dark mode it should follow the plasma theme

I commented `light = False` out

**Comment by luisbocanegra** [comment] 2022-12-08 17:45
> > What's your configuration? If you don't specify for the script (in the config or flags) to use light or dark mode it should follow the plasma theme
> 
> I commented `light = False` out. my guess is that kde-material-you autostarts before Koi and tries to apply current theme (dark theme) and Koi changes theme to light (since it is daytime) before the script completed applying the theme.
Will try to reproduce that

**Comment by luisbocanegra** [comment] 2022-12-08 22:40
>my guess is that kde-material-you autostarts before Koi and tries to apply current theme (dark theme) and Koi changes >theme to light (since it is daytime) before the script completed applying the theme.

I thought so but this is what I found:

kde-material-you-colors starts and finds that the dark/light color scheme is **not defined** in the `/.config/kdeglobals` file so it defaults to dark mode, weird that this took me more than then reboots to reproduce, and only with koi enabled

I think that, since koi starts around the same time, it probably applies the correct theme, right after the script has made its decision, or even before, I don't know, but something happens with `/.config/kdeglobals`, unsure if even has anything to do with koi

Also I'm currently using plasma from master so there's that LOL

Does it happen consistently on your end?

It could probably be solved by adding a configurable delay of some seconds, but only for the first run and probably under a flag so doesn't happen when running manually

**Comment by ShatteredSkies** [comment] 2022-12-09 02:16
> > my guess is that kde-material-you autostarts before Koi and tries to apply current theme (dark theme) and Koi changes >theme to light (since it is daytime) before the script completed applying the theme.
> 
> I thought so but this is what I found:
> 
> kde-material-you-colors starts and finds that the dark/light color scheme is **not defined** in the `/.config/kdeglobals` file so it defaults to dark mode, weird that this took me more than then reboots to reproduce, and only with koi enabled
> 
ah, that makes sense.
> I think that, since koi starts around the same time, it probably applies the correct theme, right after the script has made its decision, or even before, I don't know, but something happens with `/.config/kdeglobals`, unsure if even has anything to do with koi
> 
> Also I'm currently using plasma from master so there's that LOL
> 
> Does it happen consistently on your end?
> 
yeah, it happens consistently when I login, theme gets changed to dark.
> It could probably be solved by adding a configurable delay of some seconds, but only for the first run and probably under a flag so doesn't happen when running manually

right, a delay seems nice, waiting until dark/light theme is defined might also be an option.

**Comment by luisbocanegra** [comment] 2022-12-09 07:52
> right, a delay seems nice, waiting until dark/light theme is defined might also be an option.

Indeed, waiting for the user to select the desired theme makes more sense than using a default when no dark/light mode has been specified

**Comment by luisbocanegra** [comment] 2022-12-10 02:55
Can you try the startup delay to see if it solves the switch on boot issue? Feel free to try different values
```ini
# Enable startup delay delay before doing anything,
# useful for waiting for other utilities that may change themes on boot.
# Requires setting startup_delay below or passing --sd SECONDS
# Commented by default
use_startup_delay = True

# Startup delay in seconds
# Useful for waiting for other utilities that may change themes on boot
# Commented by default
startup_delay = 1
```

**Comment by luisbocanegra** [comment] 2022-12-10 11:30
> It works. but there are some problems:
> 
>     1. setting startup_delay to 1 or 5 makes script not check for wallpaper change until light/dark theme changed.
>        don't know why but it seems to work normally if I set startup delay to 0.
> 

That's strange, it seems to work here, are you on wayland? What prints if you don't run on startup (remove it from startup scripts) and run it manually? 

>     2. pywal is kinda messed up.
>        ![image](https://user-images.githubusercontent.com/56289692/206851013-e2751648-75aa-440e-aea1-a4d8b12453c8.png)

Yeah.. 
>        default text color is greyish and some colors are too intense (not sure if that is intentional)

I did some changes in #119 that include:

- Intense (bold) text is now brighter for dark theme
- Intense (bold) text is now darker for light theme
- Colors from 1 to 7 are no longer sorted, didn't make much sense before and since we allow custom colors those are better off If they resemble the ANSI color scheme if one wants to put that in the colors list, like me :)

This is how it looks here, note that i have the option `Konsole > Profile edit > Appearance > Draw intense colors in bold font` enabled, probably didn't help that I didn't try with a lot of wallpapers and use opacity of 90% which looks worse on screenshots...

![Screenshot_20221210_050646](https://user-images.githubusercontent.com/15076387/206851957-834732e2-be77-4f62-b818-313a1fc72726.png)

***It seemed logical to me that bold text should stand up more, but normal text is too dark now?*** of course can be improved

**Comment by ShatteredSkies** [comment] 2022-12-10 12:13
> > It works. but there are some problems:
> > ```
> > 1. setting startup_delay to 1 or 5 makes script not check for wallpaper change until light/dark theme changed.
> >    don't know why but it seems to work normally if I set startup delay to 0.
> > ```
> 
> That's strange, it seems to work here, are you on wayland? What prints out if you don't run on startup (remove it from startup scripts) and run it manually?
> 
yikes, color scheme not following wallpaper looks like to be because apply_themes is not finding active theme, startup_delay = 0 won't help in that case.
and yes, currently using wayland.
![4](https://user-images.githubusercontent.com/56289692/206854231-9ed00f18-421f-4e86-8692-7c9b842d40d8.png)

**Comment by luisbocanegra** [comment] 2022-12-10 12:23
> > > It works. but there are some problems:
> > > ```
> > > 1. setting startup_delay to 1 or 5 makes script not check for wallpaper change until light/dark theme changed.
> > >    don't know why but it seems to work normally if I set startup delay to 0.
> > > ```
> > 
> > 
> > That's strange, it seems to work here, are you on wayland? What prints out if you don't run on startup (remove it from startup scripts) and run it manually?
> 
> yikes, color scheme not following wallpaper looks like to be because apply_themes is not finding active theme, startup_delay = 0 won't help in that case. and yes, currently using wayland. ![4](https://user-images.githubusercontent.com/56289692/206854231-9ed00f18-421f-4e86-8692-7c9b842d40d8.png)

Does it also happen without koi? If so it could be a wayland bug, I cannot reproduce it on X11

**Comment by ShatteredSkies** [comment] 2022-12-10 12:39
> Does it also happen without koi? If so it could be a wayland bug, I cannot reproduce it on X11

huh.. weird, I tried X11 and apply_themes is still not finding active theme.
and yes, it happens without Koi.

**Comment by luisbocanegra** [comment] 2022-12-10 12:53
> > Does it also happen without koi? If so it could be a wayland bug, I cannot reproduce it on X11
> 
> huh.. weird, I tried X11 and apply_themes is still not finding active theme. and yes, it happens without Koi.

What if you apply a color scheme, reboot then look at the `~/.config/kdeglobals` file, does it have a `ColorScheme` property?

In my wayland session that property disappears  but there is another called `ColorSchemeHash` with a different value, so it seems that now plasma stores it that way and we should decode that?

**Comment by ShatteredSkies** [comment] 2022-12-10 13:23
> > > Does it also happen without koi? If so it could be a wayland bug, I cannot reproduce it on X11
> > 
> > 
> > huh.. weird, I tried X11 and apply_themes is still not finding active theme. and yes, it happens without Koi.
> 
> What if you apply a color scheme, reboot then look at the `~/.config/kdeglobals` file, does it have a `ColorScheme` property?
> 
> In my wayland session that property disappears but there is another called `ColorSchemeHash` with a different value, so it seems that now plasma stores it that way and we should decode that?

huh.. the `ColorScheme` property seems to persist if startup delay is set to 0, even after reboot.

**Comment by luisbocanegra** [comment] 2022-12-10 13:29
> > > > Does it also happen without koi? If so it could be a wayland bug, I cannot reproduce it on X11
> > > 
> > > 
> > > huh.. weird, I tried X11 and apply_themes is still not finding active theme. and yes, it happens without Koi.
> > 
> > 
> > What if you apply a color scheme, reboot then look at the `~/.config/kdeglobals` file, does it have a `ColorScheme` property?
> > In my wayland session that property disappears but there is another called `ColorSchemeHash` with a different value, so it seems that now plasma stores it that way and we should decode that?
> 
> huh.. the `ColorScheme` property seems to persist if startup delay is set to 0 in the config file, even after reboot.

In X11? tried in wayland and it's gone every reboot

_edited your comment instead of replying oops_

**Comment by ShatteredSkies** [comment] 2022-12-10 13:36
> > > > > Does it also happen without koi? If so it could be a wayland bug, I cannot reproduce it on X11
> > > > 
> > > > 
> > > > huh.. weird, I tried X11 and apply_themes is still not finding active theme. and yes, it happens without Koi.
> > > 
> > > 
> > > What if you apply a color scheme, reboot then look at the `~/.config/kdeglobals` file, does it have a `ColorScheme` property?
> > > In my wayland session that property disappears but there is another called `ColorSchemeHash` with a different value, so it seems that now plasma stores it that way and we should decode that?
> > 
> > 
> > huh.. the `ColorScheme` property seems to persist if startup delay is set to 0 in the config file, even after reboot.
> 
> In X11? tried in wayland and it's gone every reboot
> 
on wayland.
I'm actually not sure what's happening but as long as I have `startup_delay = 0` set in the config file, it persists
> _edited your comment instead of replying oops_

heh

**Comment by luisbocanegra** [comment] 2022-12-10 23:39
_Almost_ figured it out I think 😄
From what I can understand in this code https://invent.kde.org/plasma/plasma-workspace/-/blob/master/startkde/startplasma.cpp#L363 at least:

1. When Plasma shell loads, it reads the color scheme file from the globalsrc file
2. Then computes its sha1 hash and compares it with the one stored in the same globalsrc file
3. If the hashes are different (colors changed) , Plasma applies (reloads) the said color scheme from the config file
4. Then updates `ColorSchemeHash` with the new hash but deletes the `ColorScheme` property? Bah!
4.i How still figures out which is current color scheme and lets you edit it from system settings to then save to the original file is a mystery to me... probably caches that info somewhere else 🤷‍♂️ 
6. If the hash is the same it keeps the `ColorScheme` property

**Now, did some changes in #120 and need you to test them**  😅 

When applying color schemes to kdeglobals file also compute and store the file's hash in `ColorSchemeHash`
When starting a new session:

1. Try to read the  `ColorScheme` property
2. If not found, read the  `ColorSchemeHash` property
3. If `ColorSchemeHash`  is not empty:
3.i Get the hashes of the light and dark themes created in the last session
3.ii Compare ColorSchemeHash`  against the schemes and return true or false depending of which of the two matches
4. Now it has a mode and stores the scheme to `ColorScheme` which will be used for that session or until it disappears again 

Hopefully it works now 😆

**Comment by ShatteredSkies** [comment] 2022-12-11 00:30
> _Almost_ figured it out I think smile From what I can understand in this code https://invent.kde.org/plasma/plasma-workspace/-/blob/master/startkde/startplasma.cpp#L363 at least:
> 
>     1. When Plasma shell loads, it reads the color scheme file from the globalsrc file
> 
>     2. Then computes its sha1 hash and compares it with the one stored in the same globalsrc file
> 
>     3. If the hashes are different (colors changed) , Plasma applies (reloads) the said color scheme from the config file
> 
>     4. Then updates `ColorSchemeHash` with the new hash but deletes the `ColorScheme` property? Bah!
>        4.i How still figures out which is current color scheme and lets you edit it from system settings to then save to the original file is a mystery to me... probably caches that info somewhere else man_shrugging
> 
>     5. If the hash is the same it keeps the `ColorScheme` property
> 
> 
> **Now, did some changes in #120 and need you to test them** sweat_smile
> 
> **What changed:** When applying color schemes to kdeglobals file also compute and store the file's hash in `ColorSchemeHash` When starting a new session:
> 
>     1. Tries to read the  `ColorScheme` property
> 
>     2. If not found, reads the  `ColorSchemeHash` property
> 
>     3. If `ColorSchemeHash`  is not empty:
>        3.i Gets the hashes of the light and dark themes created in the last session
>        3.ii Compares ColorSchemeHash`  against the schemes and returns true or false depending of which of the two matches
> 
>     4. Now it has a mode and stores the scheme to `ColorScheme` which will be used for that session or until it disappears again
> 
> 
> Hopefully it works now laughing

well.. worst case, both did not match. D:
![5](https://user-images.githubusercontent.com/56289692/206880792-f77cd323-8866-4b22-987a-8514e7160814.png)

**Comment by luisbocanegra** [comment] 2022-12-11 00:44
Hmm could it be because you need to set MaterialYouDark from system settings at least once?
`cat /home/luis/.config/kdeglobals | grep ColorScheme`

**Comment by ShatteredSkies** [comment] 2022-12-11 00:47
> Hmm could it be because you need to set MaterialYouDark from system settings at least once? `cat /home/luis/.config/kdeglobals | grep ColorScheme`

huh.. I did seem to set the theme, not sure what happened there

**Comment by ShatteredSkies** [comment] 2022-12-11 01:08
> > > Hmm could it be because you need to set MaterialYouDark from system settings at least once? `cat /home/luis/.config/kdeglobals | grep ColorScheme`
> 
> > huh.. I did seem to set the theme, not sure what happened there
> 
> So it's working now? Across logins too?
> 
yeah, all working right now 👍

**Comment by luisbocanegra** [comment] 2022-12-15 03:31
Fixed in https://github.com/luisbocanegra/kde-material-you-colors/releases/tag/v1.5.0

**Closed by luisbocanegra** 2022-12-15 03:31 UTC
Labels: bug
