### ISSUE TITLE
i lack the default themes.

### ISSUE THREAD

**Issue by lunlune** [luisbocanegra/kde-material-you-colors#141] opened 2023-05-18 21:00 UTC
**Describe the bug**
if i try to launch kde-material-you-colours, it complains about the fact that there are no default themes.

**To Reproduce**
ran command kde-material-you-colors
```
[giuls@m00nbase ~]$  kde-material-you-colors
[I] kde-material-you-colors: <module>: ###### STARTED NEW SESSION ######
[D] theme_selector: apply_themes: Config: {'light': None, 'file': None, 'monitor': 0, 'plugin': 'org.kde.image', 'ncolor': 0, 'iconslight': None, 'iconsdark': None, 'pywal': None, 'pywal_light': None, 'light_blend_multiplier': 1, 'dark_blend_multiplier': 1, 'on_change_hook': None, 'sierra_breeze_buttons_color': None, 'konsole_profile': None, 'titlebar_opacity': None, 'toolbar_opacity': None, 'konsole_opacity': None, 'color': None, 'klassy_windeco_outline': None, 'custom_colors_list': None, 'darker_window_list': None, 'use_startup_delay': None, 'startup_delay': 0}
[I] plasma_utils: get_initial_mode: Couldn't find theme by name, trying to resolve theme from last stored hash...
[D] plasma_utils: get_initial_mode: Config file hash:  01662607e36cd33eacc7d7d7189f69c26b9a2cc8
Error:
[Errno 2] No such file or directory: '/home/giuls/.local/share/color-schemes/MaterialYouDark.colors'
[D] plasma_utils: get_initial_mode: Dark scheme hash:  None
Error:
[Errno 2] No such file or directory: '/home/giuls/.local/share/color-schemes/MaterialYouLight.colors'
[D] plasma_utils: get_initial_mode: Light scheme hash: None
[I] theme_selector: apply_themes: Using source (image): /usr/share/wallpapers/EndeavourOS/contents/images/3840x2160.png
[I] m3_scheme_utils: get_color_schemes: Best colors: 0:#443883,1:#512d75
[I] m3_scheme_utils: get_color_schemes: Using seed: 0:#443883
[W] theme_selector: apply_themes: No default theme found or currently active, skipping Plasma theming
```

**Expected behavior**
getting a theme based on the wallpaper

**Desktop (please complete the following information):**
 - Operating System: EndeavourOS
 - KDE Plasma Version: 5.27.5
 - KDE Frameworks Version: 5.106.0
 - Qt Version:  5.15.9
 - Graphics Platform: X11
 - Things in your system that might be relevant: ---

**Comment by luisbocanegra** [comment] 2023-05-18 21:50
Duplicate of #140 see https://github.com/luisbocanegra/kde-material-you-colors/issues/140#issuecomment-1551775432 for an explanation and temporary workaround

**Closed by luisbocanegra** 2023-05-18 21:50 UTC
