### ISSUE TITLE
Kirigami is not installed

### ISSUE THREAD

**Issue by WX580** [luisbocanegra/kde-material-you-colors#162] opened 2023-11-17 03:00 UTC
![image](https://github.com/luisbocanegra/kde-material-you-colors/assets/119598169/08c94767-a0d6-449f-8081-d15158d5fb4d)

I recently found the plasmoid widget on the kde store and upon adding it i get this error. Im not sure if this is because i didnt download the files from here and only added the widget or if im missing a package that isnt in my repository

**Comment by luisbocanegra** [comment] 2023-11-17 07:15
Duplicate of https://github.com/luisbocanegra/kde-material-you-colors/issues/159

TL;DR: Update your Plasma version or lower the imported version to one that works without breaking the widget as described here https://github.com/luisbocanegra/kde-material-you-colors/issues/159#issuecomment-1774197635

**Closed** 2023-12-11 22:33 UTC
